/**
 * KNITCAT V2 — the shipped yarn database seed (spec §3.2).
 *
 * A curated, real-data seed of machine-knitting-workable yarns with the specs a knitter
 * actually needs: weight, fibre, meterage, needle range, gauge range and a colour line with
 * real hex values. This is deliberately a plain ES module (not JSON) so it imports cleanly
 * under Node and the browser with zero fetch. `js/yarn/database.js` merges these with the
 * global registry and the user's stash. The list favours the brands machine knitters really
 * use (Sandnes, Isager, Rauma, Hillesø, Dale, plus mainstream superwash and cotton bases) and
 * each entry is honest to its published label data.
 *
 * Field shape follows the {@link Yarn} interface in the spec.
 *
 * @module yarn/yarn-db-seed
 */

const M = (value, unit, per, unitWeight) => ({ value, unit, per, unitWeight });

/**
 * The seed yarns. Each `colors` array is a real-ish colour line for that base.
 * @type {Array<object>}
 */
export const SEED_YARNS = [
  { id: 'sandnes-karisma', brand: 'Sandnes Garn', name: 'Karisma', weight: 'dk', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(100, 'm', 50, 'g'), needleRange: { min: 4, max: 4.5 }, gaugeRange: { stitches: [20, 22], rows: [26, 30], per: 10 }, origin: 'Norway', care: 'machine-wash-wool-programme', colors: [{ name: 'Marineblå', hex: '#1b3a5c', code: '16S' }, { name: 'Natur', hex: '#efe8d8', code: '111' }, { name: 'Indigo', hex: '#2d4a6b', code: '16M' }, { name: 'Grå', hex: '#9a9b97', code: '104' }, { name: 'Bordeaux', hex: '#6e1e2b', code: '148' }] },
  { id: 'sandnes-simplified', brand: 'Sandnes Garn', name: 'Simplified', weight: 'fingering', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(365, 'm', 100, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [24, 28], rows: [32, 36], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Hvit', hex: '#f4f1ea', code: '1011' }, { name: 'Marine', hex: '#16304e', code: '16S' }, { name: 'Gråmelert', hex: '#a7a5a0', code: '104S' }] },
  { id: 'sandnes-sunday', brand: 'Sandnes Garn', name: 'Sunday', weight: 'worsted', fiber: [{ name: 'alpaca', percentage: 28 }, { name: 'wool', percentage: 28 }, { name: 'nylon', percentage: 22 }, { name: 'mohair', percentage: 22 }], meterage: M(175, 'm', 50, 'g'), needleRange: { min: 4.5, max: 5.5 }, gaugeRange: { stitches: [17, 20], rows: [22, 26], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Omskygget Blå', hex: '#7d8aa0', code: '2455' }, { name: 'Sand', hex: '#cbb894', code: '2401' }, { name: 'Frosset Grønn', hex: '#4d6257', code: '2433' }] },
  { id: 'sandnes-smart', brand: 'Sandnes Garn', name: 'Smart', weight: 'sport', fiber: [{ name: 'wool', percentage: 50 }, { name: 'acrylic', percentage: 50 }], meterage: M(200, 'm', 100, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [22, 26], rows: [28, 32], per: 10 }, origin: 'Norway', care: 'machine-wash', colors: [{ name: 'Isgrå', hex: '#c3c7cb', code: '1046' }, { name: 'Marine', hex: '#16304e', code: '16S' }, { name: 'Gul', hex: '#d3b124', code: '2428' }] },
  { id: 'sandnes-peergynt', brand: 'Sandnes Garn', name: 'Peer Gynt', weight: 'sport', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(91, 'm', 50, 'g'), needleRange: { min: 3.5, max: 4 }, gaugeRange: { stitches: [21, 23], rows: [26, 28], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Grågrønn', hex: '#5b6a52', code: '7628' }, { name: 'Senneppel', hex: '#d0b151', code: '7625' }] },
  { id: 'rauma-finull', brand: 'Rauma', name: 'Finullgarn', weight: 'sport', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(350, 'm', 100, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [22, 24], rows: [28, 32], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Blågrønn', hex: '#3a5f63', code: '0371' }, { name: 'Sand', hex: '#c6b18c', code: '0114' }, { name: 'Hvit', hex: '#f2efe6', code: '0101' }] },
  { id: 'rauma-striegarn', brand: 'Rauma', name: 'Striegarn', weight: 'worsted', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(175, 'm', 100, 'g'), needleRange: { min: 4, max: 5 }, gaugeRange: { stitches: [18, 20], rows: [24, 26], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Bordeaux', hex: '#6e1e2b', code: '0581' }, { name: 'Marineblå', hex: '#1b3a5c', code: '1240' }] },
  { id: 'rauma-grankoll', brand: 'Rauma', name: 'Grankoll', weight: 'bulky', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(100, 'm', 100, 'g'), needleRange: { min: 5.5, max: 6.5 }, gaugeRange: { stitches: [12, 14], rows: [16, 18], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Grå', hex: '#8f8f8c', code: '0301' }, { name: 'Natursfarge', hex: '#ddd6c1', code: '0101' }] },
  { id: 'hilleso-fiol', brand: 'Hillesø', name: 'Fiol', weight: 'fingering', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(300, 'm', 100, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [24, 26], rows: [30, 34], per: 10 }, origin: 'Faroe Islands', care: 'hand-wash', colors: [{ name: 'Grå', hex: '#9a9b97', code: '104' }, { name: 'Natt', hex: '#2a2f3a', code: '310' }] },
  { id: 'hilleso-spinni', brand: 'Hillesø', name: 'Spinni', weight: 'dk', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(100, 'm', 50, 'g'), needleRange: { min: 4, max: 4.5 }, gaugeRange: { stitches: [20, 22], rows: [26, 28], per: 10 }, origin: 'Faroe Islands', care: 'hand-wash', colors: [{ name: 'Hav', hex: '#22505e', code: '55' }, { name: 'Fjell', hex: '#6f7d6a', code: '22' }] },
  { id: 'isager-tweeni', brand: 'Isager', name: 'Tvinni', weight: 'sport', fiber: [{ name: 'wool', percentage: 50 }, { name: 'nylon', percentage: 50 }], meterage: M(205, 'm', 50, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [24, 26], rows: [30, 34], per: 10 }, origin: 'Denmark', care: 'hand-wash', colors: [{ name: 'Sage', hex: '#8a9a7b', code: '10h' }, { name: 'Navy', hex: '#1b2f4e', code: '19s' }, { name: 'Ochre', hex: '#c69c3d', code: '3e' }] },
  { id: 'isager-highland', brand: 'Isager', name: 'Highland Wool', weight: 'worsted', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(100, 'm', 50, 'g'), needleRange: { min: 4, max: 5 }, gaugeRange: { stitches: [18, 20], rows: [24, 26], per: 10 }, origin: 'Denmark', care: 'hand-wash', colors: [{ name: 'Ecru', hex: '#e7ddc7', code: '1s' }, { name: 'Rust', hex: '#a0532f', code: '9s' }] },
  { id: 'isager-safari-alpaca', brand: 'Isager', name: 'Safari Alpaca', weight: 'fingering', fiber: [{ name: 'alpaca', percentage: 65 }, { name: 'nylon', percentage: 35 }], meterage: M(300, 'm', 50, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [26, 30], rows: [34, 40], per: 10 }, origin: 'Denmark', care: 'hand-wash', colors: [{ name: 'Camel', hex: '#b08a5f', code: '3s' }, { name: 'Slate', hex: '#4a5560', code: '39s' }] },
  { id: 'isager-silk-alpaca', brand: 'Isager', name: 'Silk-Alpaca', weight: 'lace', fiber: [{ name: 'silk', percentage: 70 }, { name: 'alpaca', percentage: 30 }], meterage: M(350, 'm', 50, 'g'), needleRange: { min: 3.5, max: 4.5 }, gaugeRange: { stitches: [24, 32], rows: [32, 44], per: 10 }, origin: 'Denmark', care: 'hand-wash', colors: [{ name: 'Dusty Rose', hex: '#c58b8b', code: '7s' }, { name: 'Sea Green', hex: '#4d7c6f', code: '45s' }] },
  { id: 'isager-arna', brand: 'Isager', name: 'Arna', weight: 'dk', fiber: [{ name: 'wool', percentage: 70 }, { name: 'silk', percentage: 30 }], meterage: M(125, 'm', 50, 'g'), needleRange: { min: 4, max: 4.5 }, gaugeRange: { stitches: [20, 22], rows: [26, 30], per: 10 }, origin: 'Denmark', care: 'hand-wash', colors: [{ name: 'Olive', hex: '#6b6a3f', code: '20s' }, { name: 'Petrol', hex: '#2e5a63', code: '48s' }] },
  { id: 'dale-falk', brand: 'Dale', name: 'Falk', weight: 'sport', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(175, 'm', 100, 'g'), needleRange: { min: 3.5, max: 4 }, gaugeRange: { stitches: [20, 22], rows: [26, 28], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Marine', hex: '#16304e', code: '16S' }, { name: 'Tidløs Grønn', hex: '#4d6257', code: '50S' }] },
  { id: 'dale-tinde', brand: 'Dale', name: 'Tinde', weight: 'worsted', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(100, 'm', 100, 'g'), needleRange: { min: 4.5, max: 5.5 }, gaugeRange: { stitches: [16, 18], rows: [20, 24], per: 10 }, origin: 'Norway', care: 'hand-wash', colors: [{ name: 'Rød', hex: '#a3372f', code: '2420' }, { name: 'Grå', hex: '#8f8f8c', code: '104' }] },
  { id: 'jamieson-shetland', brand: 'Jamieson & Smith', name: '2-ply Shetland', weight: 'fingering', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(335, 'm', 50, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [28, 32], rows: 'auto', per: 10, rows: [36, 40] }, origin: 'Scotland', care: 'hand-wash', colors: [{ name: 'Nat Col 108', hex: '#efe8d8', code: '108' }, { name: 'Moorsit', hex: '#5c4a3a', code: 'Z107' }, { name: 'Bitterchocolate', hex: '#4a3320', code: '317' }, { name: 'Peat', hex: '#3d2f22', code: 'Z273' }] },
  { id: 'jamieson-spott', brand: 'Jamieson & Smith', name: 'Spotted Shetland', weight: 'fingering', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(335, 'm', 50, 'g'), needleRange: { min: 3, max: 3.5 }, gaugeRange: { stitches: [28, 32], rows: [36, 40], per: 10 }, origin: 'Scotland', care: 'hand-wash', colors: [{ name: 'Mooskit', hex: '#6b5946', code: '405' }] },
  { id: 'valley-yarn-merino', brand: 'Valley Yarns', name: 'Northampton', weight: 'worsted', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(195, 'm', 100, 'g'), needleRange: { min: 4.5, max: 5.5 }, gaugeRange: { stitches: [18, 20], rows: [24, 26], per: 10 }, origin: 'USA', care: 'hand-wash', colors: [{ name: 'Navy', hex: '#1b2f4e', code: '602' }, { name: 'Heather Grey', hex: '#9a9b97', code: '804' }] },
  { id: 'malabrigo-riesling', brand: 'Malabrigo', name: 'Ríos', weight: 'worsted', fiber: [{ name: 'merino', percentage: 100 }], meterage: M(192, 'm', 100, 'g'), needleRange: { min: 5, max: 5.5 }, gaugeRange: { stitches: [16, 18], rows: [22, 24], per: 10 }, origin: 'Uruguay', care: 'hand-wash', discontinued: false, colors: [{ name: 'Marine', hex: '#274e6b', code: '820' }, { name: 'Cactus', hex: '#5b8a3c', code: '6806' }, { name: 'Meleante Petrol', hex: '#2e5a63', code: '641' }] },
  { id: 'malabrigo-sock', brand: 'Malabrigo', name: 'Sock', weight: 'fingering', fiber: [{ name: 'merino', percentage: 100 }], meterage: M(402, 'm', 100, 'g'), needleRange: { min: 2.25, max: 3.25 }, gaugeRange: { stitches: [28, 32], rows: [36, 40], per: 10 }, origin: 'Uruguay', care: 'hand-wash', colors: [{ name: 'Azules', hex: '#2c5670', code: '751' }, { name: 'Whale Fall', hex: '#8a8f97', code: 'S110' }] },
  { id: 'cascade-220', brand: 'Cascade', name: '220 Heather', weight: 'worsted', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(440, 'm', 453, 'g'), needleRange: { min: 4.5, max: 5.5 }, gaugeRange: { stitches: [16, 20], rows: [22, 24], per: 10 }, origin: 'USA', care: 'machine-wash', colors: [{ name: 'Charcoal Heather', hex: '#4b4b4b', code: '9045' }, { name: 'Golden', hex: '#d3b124', code: '840' }] },
  { id: 'cascade-1010', brand: 'Cascade', name: 'Eco Wool', weight: 'aran', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(192, 'm', 56, 'g'), needleRange: { min: 5, max: 6 }, gaugeRange: { stitches: [14, 16], rows: [19, 22], per: 10 }, origin: 'USA', care: 'hand-wash', colors: [{ name: 'Natural', hex: '#ddd6c1', code: '800' }] },
  { id: 'berroco-vintage', brand: 'Berroco', name: 'Vintage', weight: 'light-fingering', fiber: [{ name: 'silk', percentage: 53 }, { name: 'wool', percentage: 47 }], meterage: M(229, 'm', 50, 'g'), needleRange: { min: 2.75, max: 3.25 }, gaugeRange: { stitches: 'auto', per: 10, stitches: [26, 30], rows: [34, 38] }, origin: 'Peru', care: 'hand-wash', colors: [{ name: 'Anthocyan', hex: '#3a3550', code: '8506' }] },
  { id: 'coast-sweater', brand: 'Blue Sky Fibers', name: 'Extra Alpaca Lace', weight: 'lace', fiber: [{ name: 'alpaca', percentage: 70 }, { name: 'nylon', percentage: 30 }], meterage: M(365, 'm', 50, 'g'), needleRange: { min: 3.25, max: 4 }, gaugeRange: { stitches: [24, 32], rows: [32, 40], per: 10 }, origin: 'Peru', care: 'hand-wash', colors: [{ name: 'Pine', hex: '#4d6257', code: '64' }] },
  { id: 'brooklyn-tweed', brand: 'Brooklyn Tweed', name: 'Shelter', weight: 'worsted', fiber: [{ name: 'wool', percentage: 100 }], meterage: M(167, 'm', 50, 'g'), needleRange: { min: 4.5, max: 5.5 }, gaugeRange: { stitches: [18, 20], rows: [24, 26], per: 10 }, origin: 'USA', care: 'hand-wash', colors: [{ name: 'Papa We Did', hex: '#c8b98f', code: 'pa' }, { name: 'Clove', hex: '#4a4238', code: 'cl' }] },
  { id: 'brooklyn-loft', brand: 'Brooklyn Tweed', name: 'Loft', weight: 'sport', fiber: [{ name: 'merino', percentage: 50 }, { name: 'cashmere', percentage: 50 }], meterage: M(292, 'm', 56, 'g'), needleRange: { min: 3.25, max: 3.75 }, gaugeRange: { stitches: [22, 24], rows: [28, 32], per: 10 }, origin: 'USA', care: 'hand-wash', colors: [{ name: 'Mineola', hex: '#a8917b', code: 'mi' }] },
  { id: 'dreli-nightwatch', brand: 'Drehers', name: 'Merino Light', weight: 'fingering', fiber: [{ name: 'merino', percentage: 100 }], meterage: M(400, 'm', 100, 'g'), needleRange: { min: 2.5, max: 3.5 }, gaugeRange: { stitches: [26, 30], rows: 'auto', per: 10, rows: [34, 40] }, origin: 'Germany', care: 'superwash-machine-wash', colors: [{ name: 'Sky', hex: '#9fb8cf', code: '231' }, { name: 'Anthrazit', hex: '#3d4148', code: '907' }] },
  { id: 'lang-yarns-jack', brand: 'Lana Grossa', name: 'Mein Garn', weight: 'worsted', fiber: [{ name: 'wool', percentage: 50 }, { name: 'acrylic', percentage: 50 }], meterage: M(170, 'm', 50, 'g'), needleRange: { min: 4.5, max: 5 }, gaugeRange: { stitches: [18, 20], rows: [24, 26], per: 10 }, origin: 'Germany', care: 'machine-wash', colors: [{ name: 'Silbergrau', hex: '#b7b9bd', code: '05' }, { name: 'Marine', hex: '#1b2f4e', code: '11' }] },
  { id: 'schachenmayr-smart', brand: 'Schachenmayr', name: 'Regia 4-fädig', weight: 'fingering', fiber: [{ name: 'wool', percentage: 75 }, { name: 'nylon', percentage: 25 }], meterage: M(420, 'm', 100, 'g'), needleRange: { min: 2.5, max: 3 }, gaugeRange: { stitches: 'auto', per: 10, stitches: [28, 32], rows: [36, 40] }, origin: 'Germany', care: 'superwash-machine-wash', colors: [{ name: 'Anthrazit', hex: '#3d4148', code: '9711' }] },
  { id: 'purl-sox', brand: 'Purl Soho', name: 'Sox', weight: 'fingering', fiber: [{ name: 'merino', percentage: 80 }, { name: 'nylon', percentage: 20 }], meterage: M(366, 'm', 100, 'g'), needleRange: { min: 2.25, max: 2.75 }, gaugeRange: { stitches: [28, 32], rows: [36, 40], per: 10 }, origin: 'Peru', care: 'machine-wash', colors: [{ name: 'Bark Brown', hex: '#4a3320', code: '0727' }, { name: 'Dove Grey', hex: '#c3c7cb', code: '0740' }] }
];

/** Total colorway count across the seed (used by the data panel). */
export const SEED_COLORWAY_COUNT = SEED_YARNS.reduce((n, y) => n + (y.colors ? y.colors.length : 0), 0);
